In [1]:
import pandas as pd
file_path = '/Users/xiaoyufan/Desktop/5311/hw3/yelp_boston.csv'
df = pd.read_csv(file_path)
df

,name,url,review_count,categories_json,rating,snippet_text,location_json,neighborhood,latitude,longitude,search category
0,Wheelhouse,http://www.yelp.com/biz/wheelhouse-boston-3,101,"[[""Breakfast & Brunch"", ""breakfast_brunch""], [...",4.5,"After going to Wheelhouse, you'll never order ...","{""cross_streets"": ""Milk St & Batterymarch Arm""...",Financial District,42.357926,-71.053962,restaurants
1,Tenoch Mexican,http://www.yelp.com/biz/tenoch-mexican-boston,121,"[[""Mexican"", ""mexican""]]",4.5,"So it's official, folks. We've finished our sa...","{""city"": ""Boston"", ""display_address"": [""3 Lewi...",North End,42.363309,-71.051800,restaurants
2,O Ya,http://www.yelp.com/biz/o-ya-boston,450,"[[""Japanese"", ""japanese""]]",4.5,My husband and I came here to celebrate our 20...,"{""city"": ""Boston"", ""display_address"": [""9 E St...",Waterfront,42.351408,-71.056867,restaurants
3,Locale,http://www.yelp.com/biz/locale-boston,121,"[[""Italian"", ""italian""], [""Pizza"", ""pizza""]]",4.5,Truly thankful that we stumbled on Locale whil...,"{""cross_streets"": ""Fleet St & Tileston St"", ""c...",North End,42.365085,-71.053187,restaurants
4,Neptune Oyster,http://www.yelp.com/biz/neptune-oyster-boston,2487,"[[""Seafood"", ""seafood""], [""Live/Raw Food"", ""ra...",4.5,Best lobster roll on the whole trip..... and I...,"{""cross_streets"": ""Hull St & Stillman St"", ""ci...",North End,42.363618,-71.056012,restaurants
...,...,...,...,...,...,...,...,...,...,...,...
338,El Madina,http://www.yelp.com/biz/el-madina-revere,8,"[[""Mediterranean"", ""mediterranean""], [""Middle ...",4.5,I went in around closing tonight because I was...,"{""city"": ""Revere"", ""display_address"": [""148 Sq...",NaN,42.423248,-71.009514,ethnicmarkets
339,The Shops at Porter,http://www.yelp.com/biz/the-shops-at-porter-ca...,79,"[[""Japanese"", ""japanese""], [""Ethnic Food"", ""et...",4.0,This is like a small (chibi) version of the Ja...,"{""city"": ""Cambridge"", ""display_address"": [""Uni...",Porter Square,42.387192,-71.118778,ethnicmarkets
340,Bazaar International Gourmet,http://www.yelp.com/biz/bazaar-international-g...,52,"[[""Ethnic Food"", ""ethnicmarkets""], [""Grocery"",...",4.0,"The Bazaar at 1432 Beacon Street, Brookline Ma...","{""city"": ""Brookline"", ""display_address"": [""143...",Coolidge Corner,42.341065,-71.126470,ethnicmarkets
341,G Mart 2 Supermarket,http://www.yelp.com/biz/g-mart-2-supermarket-b...,48,"[[""Grocery"", ""grocery""], [""Ethnic Food"", ""ethn...",4.0,Everything is inexpensive! I was so surprised ...,"{""cross_streets"": ""Beach St & Tufts St"", ""city...",Waterfront,42.351569,-71.058365,ethnicmarkets
342,Bonne Chance Cafe & Bakery,http://www.yelp.com/biz/bonne-chance-cafe-and-...,22,"[[""Bakeries"", ""bakeries""], [""Coffee & Tea"", ""c...",4.0,I have to say.... I've not had anything else o...,"{""cross_streets"": ""Traverse St & Market St"", ""...",NaN,42.364044,-71.059463,ethnicmarkets

In [3]:
search_category = df['search category'].value_counts()
print(search_category)

search category
restaurants      20
vietnamese       20
donuts           20
sandwiches       20
pizza            20
indpak           20
sushi            20
japanese         20
thai             20
mexican          19
ethnicmarkets    19
newamerican      19
coffee           18
cafes            18
french           18
italian          18
bakeries         17
chinese          17
Name: count, dtype: int64

In [4]:
categories_json = df['categories_json'].value_counts()
print(categories_json)

categories_json
[["Thai", "thai"]]                                                                          14
[["Mexican", "mexican"]]                                                                    13
[["Sushi Bars", "sushi"], ["Japanese", "japanese"]]                                         10
[["Coffee & Tea", "coffee"]]                                                                10
[["Indian", "indpak"]]                                                                      10
                                                                                            ..
[["Cafes", "cafes"], ["Turkish", "turkish"], ["Falafel", "falafel"]]                         1
[["Coffee & Tea", "coffee"], ["Sandwiches", "sandwiches"], ["Cafes", "cafes"]]               1
[["Sandwiches", "sandwiches"], ["Burgers", "burgers"]]                                       1
[["Diners", "diners"], ["Sandwiches", "sandwiches"], ["Salad", "salad"]]                     1
[["Bakeries", "bakeries"], ["Coffee & Tea", "coffee"], ["Ethnic Food", "ethnicmarkets"]]     1
Name: count, Length: 170, dtype: int64

In [5]:
neighborhood = df['neighborhood'].value_counts()
print(neighborhood)

neighborhood
North End             31
South End             29
Back Bay              29
Chinatown             27
Downtown              22
Waterfront            20
East Boston           20
Allston/Brighton      20
Financial District    13
South Boston          11
Dorchester             9
Beacon Hill            8
Fenway                 5
Mission Hill           3
Kendall Square/MIT     3
Charlestown            3
Jamaica Plain          2
Harvard Square         2
Teele Square           2
Porter Square          2
West Roxbury           2
Inman Square           1
North Cambridge        1
Coolidge Corner        1
Name: count, dtype: int64

In [6]:
rating = df['rating'].value_counts()
print(rating)

rating
4.0    199
4.5    115
3.5     22
5.0      7
Name: count, dtype: int64

In [7]:
review_count = df['review_count'].value_counts()
review_count1 = review_count[review_count > 50000 ]
print(review_count)

review_count
89      6
121     6
17      5
40      5
16      4
       ..
1290    1
1115    1
273     1
151     1
48      1
Name: count, Length: 211, dtype: int64

In [11]:
columns_to_drop = ['latitude', 'longitude']
df = df.drop(columns=columns_to_drop, errors='ignore')
df
df.to_csv('/Users/xiaoyufan/Desktop/yelp_boston_new.csv', index=False)